### ISSUE TITLE
can not create icons

### ISSUE THREAD

**Issue by WuglyakBolgoink** [SamVerschueren/gulp-cordova-icon#22]
H!

with ImageMagick (exist in PATH too) plugin doesn't work correct... better say: did NOTHING.

After I  installed GraficImage from official page and add it in PATH and install, "maybe not need it" via "npm isntall -g gm" plugin created all icons...

**Comment by SamVerschueren** [comment]
The documentation indeed is incorrect. Installing ImageMagick doesn't work, you have to install GraphicsMagick. I am working on a fix that doesn't require the user to manually install GraphicsMagick.

**Comment by WuglyakBolgoink** [comment]
Thank you for information!

Is it possible correct path too?

In my task I do:

``` javascript
 gulp.task("cordova:android:rebuild", function() {
        return gulp
            .src(cordova.path.project.dir)
            .pipe(cIcon(cordova.path.icon))
            .pipe(cAndroid(cordova.path.keys))
            .pipe(rename(function(path) {
                path.basename = cordova.appName;
            }))
            .pipe(gulp.dest(cordova.path.apk));
    });
```

**_cordova.path.icon**_ is relative to **CORDOVA** folder and not to my Project-Folder.
if I write **"res/icon.png"** plugin search this icon as **X:/project/cordova/res/icon.png** and not as  **X:/project/src/images/app_icons/icon.png** and copy this file into **.../cordova/res/** folder and do after operations with image to create a different icons in drawable-folders...

or do I something wrong?

Sorry for my English :(

**Comment by SamVerschueren** [comment]
Where is the `gulpfile.js` located? The path of the icon is relative from the working directory (e.g. the directory where the `gulpfile.js` is stored).

For example

```
my-app
  |-- gulpfile.js
  |-- src
    |-- res
      |-- icon.png
```

``` js
gulp.task('cordova:android', function () {
    return gulp.src('dist')
        .pipe(icon('src/res/icon.png'))
        .pipe(android())
        .pipe(gulp.dest('apks'));
});
```

**Comment by WuglyakBolgoink** [comment]
**_gulpfile.js**_ is on **X:/project/**-Folder

**Comment by SamVerschueren** [comment]
The plugin works in 2 steps. The first step is to copy the source icon (e.g. `src/res/icon.png` in my example) to the `cordova/res` directory. It also copies a [`before_prepare`](https://github.com/SamVerschueren/gulp-cordova-icon/blob/master/hooks/before_prepare/icon.js) hook to the cordova directory which generates the icon when building the platform. This approach makes sure it only builds the icons for the platform you are building for instead of generating them for all the platforms and selecting the ones it need.

So the source icon `X:/project/src/images/app_icons/icon.png` should be copied to `X:/project/cordova/res/icon.png` first. So make sure, that source file exists. Your path in the `gulpfile.js` should be `src/images/app_icons/icon.png`.

**Comment by SamVerschueren** [comment]
ping @cyberkatze 

Any update on this? Is it resolved?

**Comment by SamVerschueren** [comment]
Closing due to lack of response. Please reopen if you still experience the same issue.
